services:
  mariadb:
    image: mariadb:11.2.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    container_name: Grades-mariadb
    volumes:
      - ./mariadb:/var/lib/mariadb/data